version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dove
  app:
    image: laun23/dover:0.0.3
    restart: always
    container_name: dover-container
    ports:
      - 8081:8088
    environment:
      DBMS_CONNECTION: jdbc:postgresql://postgres-container:5432/dove
      DBMS_USERNAME: postgres
      DBMS_PASSWORD: 123
      ACCESS_TOKEN_KEY: gBdAWm7gixEyBRGV6bqBFx3QgTd//gJEy/Fp77nL7XPlReTDVDhdAC+lJVk/i3M/
      REFRESH_TOKEN_KEY: v0yHyjTfJpLdzGC1A6yHEFZWOT6jQWUVFAkCcKXofODjxidglVrHVpBK9+NsZcSY