token:
  access_token_key: ${ACCESS_TOKEN_KEY}      #32 bytes
  access_token_expiration: 604800 #2 hours: 7200
  refresh_token_key: ${REFRESH_TOKEN_KEY}     #32 bytes
  refresh_token_expiration: 604800 #7 days